version: '3.1'

services:
  redis:
    image: redis:alpine
    volumes:
      - /redis_data:/data/redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  mongodb:
    image : mongo
    volumes:
    - /mongo_data:/data/mongo
    ports:
    - 27017:27017
    restart: always
volumes:
  postgres_data:
  redis_data:
  mongo_data:
